-- 그룹별 조건에 맞는 식당 목록 출력하기
WITH VIP AS(
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(REVIEW_ID) DESC LIMIT 1
)
SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM 
    REST_REVIEW 
    JOIN MEMBER_PROFILE USING (MEMBER_ID)
    JOIN VIP USING (MEMBER_ID)
ORDER BY REVIEW_DATE, REVIEW_TEXT