# Generated by Django 4.2 on 2023-04-17 07:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0002_article_like_users_comment_like_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='dislike_users',
            field=models.ManyToManyField(related_name='dislike_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='dislike_users',
            field=models.ManyToManyField(related_name='dislike_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
