-- 우유와 요거트가 담긴 장바구니

    SELECT CART_ID FROM CART_PRODUCTS
    INNER JOIN
    (SELECT CART_ID FROM CART_PRODUCTS WHERE NAME LIKE "Yogurt") YOGURT
    USING (CART_ID)
    WHERE NAME LIKE "Milk"
    ORDER BY CART_ID

