-- 코드를 입력하세요
WITH RECURSIVE
HOURS (HOUR) AS
(
SELECT 0
UNION ALL
SELECT HOUR+1 FROM HOURS WHERE HOUR < 23
)
SELECT 
    A.HOUR, 
    CASE
        WHEN B.COUNT > 0 THEN B.COUNT
        ELSE 0
    END AS COUNT
FROM HOURS A 
LEFT JOIN 
    (
    SELECT
        HOUR(DATETIME) AS HOUR,
        COUNT(ANIMAL_ID) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR
    ) B
ON A.HOUR = B.HOUR
GROUP BY HOUR
ORDER BY HOUR