-- 년, 월, 성별 별 상품 구매 회원 수 구하기
SELECT 
    YEAR(SALES_DATE) YEAR,
    MONTH(SALES_DATE) MONTH,
    GENDER,
    COUNT(DISTINCT USER_ID) AS USERS
FROM ONLINE_SALE LEFT JOIN USER_INFO USING (USER_ID)
GROUP BY YEAR, MONTH, GENDER
HAVING GENDER IS NOT NULL
ORDER BY YEAR, MONTH, GENDER