-- 저자 별 카테고리 별 매출액 집계하기
WITH S AS (
    SELECT BOOK_ID, SUM(SALES) AS SALES FROM BOOK_SALES
    WHERE MONTH(SALES_DATE) = 1 AND YEAR(SALES_DATE) = 2022
    GROUP BY BOOK_ID
)
SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(SALES*PRICE) AS TOTAL_SALES
FROM S LEFT JOIN BOOK USING (BOOK_ID) LEFT JOIN AUTHOR USING (AUTHOR_ID)
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC
