-- 취소되지 않은 진료 예약 조회하기
WITH 
APNT AS (
    SELECT *, MDDR_ID AS DR_ID FROM APPOINTMENT
    WHERE APNT_CNCL_YN = "N" AND DATE(APNT_YMD) = "2022-04-13"
),
DCTR AS (
    SELECT *  FROM DOCTOR
    WHERE MCDP_CD = "CS"
)
SELECT APNT_NO, PT_NAME, PT_NO, DCTR.MCDP_CD, DR_NAME, APNT_YMD
FROM 
    APNT 
    INNER JOIN DCTR USING (DR_ID)
    LEFT JOIN PATIENT USING (PT_NO)
ORDER BY APNT_YMD
