-- 코드를 입력하세요
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO 
INNER JOIN 
    (SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX_F FROM REST_INFO GROUP BY FOOD_TYPE)
AS T USING (FOOD_TYPE)
WHERE REST_INFO.FAVORITES = T.MAX_F
ORDER BY FOOD_TYPE DESC

