-- 자동차 대여 기록 별 대여 금액 구하기
# WITH H AS (
#     SELECT *, DATEDIFF(END_DATE, START_DATE)-1 AS DURATION
#     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# ),
# F AS (
#     SELECT 
#         CAR_ID, CAR_TYPE, DAILY_FEE, 
#         CAST(REPLACE(DURATION_TYPE, "일 이상", "") AS SIGNED) AS DURATION_TYPE, 
#         CAST(REPLACE(DISCOUNT_RATE, "%", "") AS SIGNED)AS DISCOUNT_RATE
#     FROM CAR_RENTAL_COMPANY_CAR TYPE
#     CROSS JOIN (
#         SELECT * FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
#         UNION ALL
#         SELECT 0 AS PLAN_ID, CAR_TYPE, 0 AS DURATION_TYPE, 0 AS DISCOUNT_RATE 
#         FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
#     ) AS P 
#     USING (CAR_TYPE)
# )
# SELECT 
#     HISTORY_ID, MIN(ROUND(DAILY_FEE*(1 - DISCOUNT_RATE/100)*DURATION, 0)) AS FEE
# FROM H LEFT JOIN F USING (CAR_ID)
# WHERE DURATION_TYPE <= DURATION
# GROUP BY HISTORY_ID
# ORDER BY FEE DESC, HISTORY_ID DESC

WITH H AS (
    SELECT *, DATEDIFF(END_DATE, START_DATE) + 1 AS DURATION
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
),
F AS (
    SELECT 
        CAR_ID, CAR_TYPE, DAILY_FEE, 
        CAST(REPLACE(DURATION_TYPE, "일 이상", "") AS SIGNED) AS DURATION_TYPE, 
        CAST(REPLACE(DISCOUNT_RATE, "%", "") AS SIGNED)AS DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_CAR TYPE
    CROSS JOIN (
        SELECT * FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
        UNION ALL
        SELECT 
            0 AS PLAN_ID,
            CAR_TYPE,
            1 AS DURATION_TYPE,
            0 AS DISCOUNT_RATE 
        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
        GROUP BY CAR_TYPE
    ) AS P 
    USING (CAR_TYPE)
)
SELECT 
    HISTORY_ID, MIN(ROUND(DAILY_FEE*(1 - DISCOUNT_RATE/100)*DURATION, 0)) AS FEE
# SELECT
#     HISTORY_ID, DAILY_FEE, DURATION_TYPE, DISCOUNT_RATE/100, DURATION
FROM H LEFT JOIN F USING (CAR_ID)
WHERE DURATION_TYPE <= DURATION AND CAR_TYPE = "트럭"
GROUP BY HISTORY_ID
ORDER BY FEE DESC, HISTORY_ID DESC
# ORDER BY HISTORY_ID, DISCOUNT_RATE