-- 코드를 입력하세요
# "2022-10-16"
SELECT DISTINCT CAR_ID,
CASE WHEN C IS NULL THEN "대여 가능" else "대여중" end as AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
LEFT JOIN
(SELECT CAR_ID, COUNT(HISTORY_ID) AS C
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE DATEDIFF(DATE(START_DATE), DATE('2022-10-16')) <= 0 
  AND DATEDIFF(DATE('2022-10-16'), DATE(END_DATE)) <= 0
GROUP BY CAR_ID) as T2 using (CAR_ID)
ORDER BY CAR_ID DESC



# SELECT CAR_ID, COUNT(HISTORY_ID) AS C
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE 
#     DATEDIFF(DATE(START_DATE), DATE('2022-10-16')) <= 0 
#     AND DATEDIFF(DATE('2022-10-16'), DATE(END_DATE)) <= 0
# GROUP BY CAR_ID