-- 코드를 입력하세요
SELECT CATEGORY, SUM(SUM_SALES) AS TOTAL_SALES
FROM BOOK INNER JOIN (SELECT BOOK_ID, SUM(SALES) AS SUM_SALES FROM BOOK_SALES WHERE SALES_DATE BETWEEN "2022-01-01" AND "2022-01-31" GROUP BY BOOK_ID) AS SALES USING (BOOK_ID)
GROUP BY CATEGORY
ORDER BY CATEGORY