-- 5월 식품들의 총매출 조회하기


SELECT PRODUCT_ID, PRODUCT_NAME, SUM(AMOUNT * PRICE) AS TOTAL_SALES
FROM FOOD_ORDER LEFT JOIN FOOD_PRODUCT USING(PRODUCT_ID)
WHERE DATE(PRODUCE_DATE) BETWEEN "2022-05-01" AND "2022-05-31"
GROUP BY PRODUCT_ID, PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC
