-- 코드를 입력하세요
SELECT DISTINCT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
INNER JOIN 
    (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_CAR WHERE CAR_TYPE = "세단") 
    AS SEDAN USING (CAR_ID)
WHERE MONTH(START_DATE) = 10
ORDER BY CAR_ID DESC
