-- 코드를 입력하세요
WITH AVG_S AS (
    SELECT REST_ID, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
    FROM REST_REVIEW
    GROUP BY REST_ID
),
S_REST AS (
    SELECT *
    FROM REST_INFO
    WHERE ADDRESS LIKE "서울%"
)
SELECT REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, SCORE 
FROM S_REST INNER JOIN AVG_S USING (REST_ID)
ORDER BY SCORE DESC, FAVORITES DESC